server:
  port: 1001
spring:
  application:
    name: spring-ai-tool-calling-example
  ai:
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        enabled: true
        options:
          model: deepseek-chat

# 开启日志输出
logging:
  level:
    org.springframework.ai: DEBUG


